name = "quiz-be"
main = "src/index.ts"
compatibility_date = "2026-05-26"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8789

[[d1_databases]]
binding = "DB"
database_name = "quiz-db"
database_id = "5524c2fb-27b3-433d-a0b2-f031c80c541d"
migrations_dir = "drizzle"
